#server:
#  port: ${random.int(8080,9000)}

# H2 DB
spring:
  h2:
    console:
      enabled: true
      path: '/h2-console-log'

  datasource:
    url: 'jdbc:h2:mem:local'
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 600000
      maxLifetime: 2000000
      connectionTimeout: 30000